### ISSUE TITLE
Upgrade UBI images to 8.3

### ISSUE THREAD

**Issue by leochr** [ibmruntimes/ci.docker#102]
We have seen a few security vulnerability reports against the UBI 8.2 distribution that IBM Java uses (i.e. https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/jre/ubi/Dockerfile). The version 8.3 is available (https://catalog.redhat.com/software/containers/ubi8/ubi/5c359854d70cc534b3a3784e), so this issue is to request that the images are upgraded to use UBI 8.3. Thank you.

**Comment by leochr** [comment]
fyi @dinogun @davemula

**Comment by jayasg12** [comment]
Hi @leochr UBI image 8.2 is the stable version which can be used for ibm java, whenever there is an update to ubi:8.2 latest image,  ibm java docker image pulls the changes in next java delivery cycle . Can you please confirm if latest ubi:8.2 image solves security vulnerability issue ? Please share CVE number of vulnerability reported.

**Comment by leochr** [comment]
@jayasg12 The latest UBI 8.2 image has 27 vulnerabilities (full list below), while UBI 8.3 doesn't have any.

Used the `docker scan` feature. For example: docker scan registry.access.redhat.com/ubi8/ubi:8.2

List of vulnerabilities: 

Testing registry.access.redhat.com/ubi8/ubi:8.2...

✗ Low severity vulnerability found in systemd-pam
  Description: RHSA-2020:4553
  Info: https://snyk.io/vuln/SNYK-RHEL8-SYSTEMDPAM-1036770
  Introduced through: systemd-pam@239-31.el8_2.2
  From: systemd-pam@239-31.el8_2.2
  Fixed in: 0:239-40.el8

✗ Low severity vulnerability found in systemd-libs
  Description: RHSA-2020:4553
  Info: https://snyk.io/vuln/SNYK-RHEL8-SYSTEMDLIBS-1036771
  Introduced through: systemd-libs@239-31.el8_2.2
  From: systemd-libs@239-31.el8_2.2
  Fixed in: 0:239-40.el8

✗ Low severity vulnerability found in systemd
  Description: RHSA-2020:4553
  Info: https://snyk.io/vuln/SNYK-RHEL8-SYSTEMD-1036773
  Introduced through: systemd@239-31.el8_2.2
  From: systemd@239-31.el8_2.2
  Fixed in: 0:239-40.el8

✗ Low severity vulnerability found in openssl-libs
  Description: RHSA-2020:4514
  Info: https://snyk.io/vuln/SNYK-RHEL8-OPENSSLLIBS-1036698
  Introduced through: openssl-libs@1:1.1.1c-15.el8
  From: openssl-libs@1:1.1.1c-15.el8
  Fixed in: 1:1.1.1g-11.el8

✗ Low severity vulnerability found in libpcap
  Description: RHSA-2020:4547
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBPCAP-1036784
  Introduced through: libpcap@14:1.9.0-3.el8
  From: libpcap@14:1.9.0-3.el8
  Fixed in: 14:1.9.1-4.el8

✗ Medium severity vulnerability found in vim-minimal
  Description: RHSA-2020:4453
  Info: https://snyk.io/vuln/SNYK-RHEL8-VIMMINIMAL-1036873
  Introduced through: vim-minimal@2:8.0.1763-13.el8
  From: vim-minimal@2:8.0.1763-13.el8
  Fixed in: 2:8.0.1763-15.el8

✗ Medium severity vulnerability found in sqlite-libs
  Description: RHSA-2020:4442
  Info: https://snyk.io/vuln/SNYK-RHEL8-SQLITELIBS-1036703
  Introduced through: sqlite-libs@3.26.0-6.el8
  From: sqlite-libs@3.26.0-6.el8
  Fixed in: 0:3.26.0-11.el8

✗ Medium severity vulnerability found in python3-pip-wheel
  Description: RHSA-2020:4432
  Info: https://snyk.io/vuln/SNYK-RHEL8-PYTHON3PIPWHEEL-1036948
  Introduced through: python3-pip-wheel@9.0.3-16.el8
  From: python3-pip-wheel@9.0.3-16.el8
  Fixed in: 0:9.0.3-18.el8

✗ Medium severity vulnerability found in python3-libxml2
  Description: RHSA-2020:4479
  Info: https://snyk.io/vuln/SNYK-RHEL8-PYTHON3LIBXML2-1036403
  Introduced through: python3-libxml2@2.9.7-7.el8
  From: python3-libxml2@2.9.7-7.el8
  Fixed in: 0:2.9.7-8.el8

✗ Medium severity vulnerability found in python3-libs
  Description: RHSA-2020:4433
  Info: https://snyk.io/vuln/SNYK-RHEL8-PYTHON3LIBS-1036801
  Introduced through: python3-libs@3.6.8-23.el8
  From: python3-libs@3.6.8-23.el8
  Fixed in: 0:3.6.8-31.el8

✗ Medium severity vulnerability found in platform-python
  Description: RHSA-2020:4433
  Info: https://snyk.io/vuln/SNYK-RHEL8-PLATFORMPYTHON-1036802
  Introduced through: platform-python@3.6.8-23.el8
  From: platform-python@3.6.8-23.el8
  Fixed in: 0:3.6.8-31.el8

✗ Medium severity vulnerability found in pcre2
  Description: RHSA-2020:4539
  Info: https://snyk.io/vuln/SNYK-RHEL8-PCRE2-1036878
  Introduced through: pcre2@10.32-1.el8
  From: pcre2@10.32-1.el8
  Fixed in: 0:10.32-2.el8

✗ Medium severity vulnerability found in libxml2
  Description: RHSA-2020:4479
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBXML2-1036404
  Introduced through: libxml2@2.9.7-7.el8
  From: libxml2@2.9.7-7.el8
  Fixed in: 0:2.9.7-8.el8

✗ Medium severity vulnerability found in libssh-config
  Description: RHSA-2020:4545
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBSSHCONFIG-1035955
  Introduced through: libssh-config@0.9.0-4.el8
  From: libssh-config@0.9.0-4.el8
  Fixed in: 0:0.9.4-2.el8

✗ Medium severity vulnerability found in libssh
  Description: RHSA-2020:4545
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBSSH-1035954
  Introduced through: libssh@0.9.0-4.el8
  From: libssh@0.9.0-4.el8
  Fixed in: 0:0.9.4-2.el8

✗ Medium severity vulnerability found in libsolv
  Description: RHSA-2020:4508
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBSOLV-1036767
  Introduced through: libsolv@0.7.7-1.el8
  From: libsolv@0.7.7-1.el8
  Fixed in: 0:0.7.11-1.el8

✗ Medium severity vulnerability found in libgcrypt
  Description: RHSA-2020:4482
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBGCRYPT-1036854
  Introduced through: libgcrypt@1.8.3-4.el8
  From: libgcrypt@1.8.3-4.el8
  Fixed in: 0:1.8.5-4.el8

✗ Medium severity vulnerability found in libcurl
  Description: RHSA-2020:4599
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBCURL-1036909
  Introduced through: libcurl@7.61.1-12.el8
  From: libcurl@7.61.1-12.el8
  Fixed in: 0:7.61.1-14.el8

✗ Medium severity vulnerability found in libarchive
  Description: RHSA-2020:4443
  Info: https://snyk.io/vuln/SNYK-RHEL8-LIBARCHIVE-1035949
  Introduced through: libarchive@3.3.2-8.el8_1
  From: libarchive@3.3.2-8.el8_1
  Fixed in: 0:3.3.2-9.el8

✗ Medium severity vulnerability found in gnupg2
  Description: RHSA-2020:4490
  Info: https://snyk.io/vuln/SNYK-RHEL8-GNUPG2-1036807
  Introduced through: gnupg2@2.2.9-1.el8
  From: gnupg2@2.2.9-1.el8
  Fixed in: 0:2.2.20-2.el8

✗ Medium severity vulnerability found in glibc-minimal-langpack
  Description: RHSA-2020:4444
  Info: https://snyk.io/vuln/SNYK-RHEL8-GLIBCMINIMALLANGPACK-1036516
  Introduced through: glibc-minimal-langpack@2.28-101.el8
  From: glibc-minimal-langpack@2.28-101.el8
  Fixed in: 0:2.28-127.el8

✗ Medium severity vulnerability found in glibc-common
  Description: RHSA-2020:4444
  Info: https://snyk.io/vuln/SNYK-RHEL8-GLIBCCOMMON-1036473
  Introduced through: glibc-common@2.28-101.el8
  From: glibc-common@2.28-101.el8
  Fixed in: 0:2.28-127.el8

✗ Medium severity vulnerability found in glibc
  Description: RHSA-2020:4444
  Info: https://snyk.io/vuln/SNYK-RHEL8-GLIBC-1036537
  Introduced through: glibc@2.28-101.el8
  From: glibc@2.28-101.el8
  Fixed in: 0:2.28-127.el8

✗ Medium severity vulnerability found in expat
  Description: RHSA-2020:4484
  Info: https://snyk.io/vuln/SNYK-RHEL8-EXPAT-1035951
  Introduced through: expat@2.2.5-3.el8
  From: expat@2.2.5-3.el8
  Fixed in: 0:2.2.5-4.el8

✗ Medium severity vulnerability found in cyrus-sasl-lib
  Description: RHSA-2020:4497
  Info: https://snyk.io/vuln/SNYK-RHEL8-CYRUSSASLLIB-1036037
  Introduced through: cyrus-sasl-lib@2.1.27-1.el8
  From: cyrus-sasl-lib@2.1.27-1.el8
  Fixed in: 0:2.1.27-5.el8

✗ Medium severity vulnerability found in curl
  Description: RHSA-2020:4599
  Info: https://snyk.io/vuln/SNYK-RHEL8-CURL-1036910
  Introduced through: curl@7.61.1-12.el8
  From: curl@7.61.1-12.el8
  Fixed in: 0:7.61.1-14.el8

✗ Medium severity vulnerability found in cryptsetup-libs
  Description: RHSA-2020:4542
  Info: https://snyk.io/vuln/SNYK-RHEL8-CRYPTSETUPLIBS-1036464
  Introduced through: cryptsetup-libs@2.2.2-1.el8
  From: cryptsetup-libs@2.2.2-1.el8
  Fixed in: 0:2.3.3-2.el8



Organization:      undefined
Package manager:   rpm
Project name:      docker-image|registry.access.redhat.com/ubi8/ubi
Docker image:      registry.access.redhat.com/ubi8/ubi:8.2
Platform:          linux/amd64

Tested 179 dependencies for known vulnerabilities, found 27 vulnerabilities.

**Comment by leochr** [comment]
resolved by https://github.com/ibmruntimes/ci.docker/pull/107. Thank you!
