### ISSUE TITLE
Memory management is not correct when using cgroup v2 

### ISSUE THREAD

**Issue by lgrateau** [ibmruntimes/ci.docker#124]
With:
 *  The latest docker desktop for Mac implementation (after 4.3) https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-430 
 * Podman **V3.3.1** 
 
The computation of the memory of the JVM is not correct and cause **Out Of Memory**:
```
 docker run -m 4GB --rm ibmjava:8-jre java -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 512.00M
    Ergonomics Machine Class: client
    Using VM: IBM J9 VM

```
This is not the case with openjdk :
```
docker run -m 4GB --rm openjdk:8-jre java -XshowSettings:vm -version
VM settings:
    Max. Heap Size (Estimated): 2.49G
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM
```

The root cause is probably due to the **CGroup V2** support.

If we force use of cgroup v1 in Docker Desktop (with dev build listed on https://github.com/docker/for-mac/issues/6073#issuecomment-993274406) it works again fine:

```
 docker run -m 4GB  --rm  ibmjava:8-jre java  -XshowSettings:vm  -version
VM settings:
    Max. Heap Size (Estimated): 3.00G
    Ergonomics Machine Class: client
    Using VM: IBM J9 VM
java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20211025_01(SR7))
```

**Comment by PYLochou** [comment]
With podman running with cgroup on RHEL 7 or cgroupv2 on RHEL 8, I get different results with ibmjava, compared to openjdk and store/oracle/serverjre:
````console
[root@junketed1 ~]# podman run -m 4g --rm ibmjava:8-jre java -XshowSettings:vm  -version
VM settings:
    Max. Heap Size (Estimated): 512.00M
    Ergonomics Machine Class: client
    Using VM: IBM J9 VM

java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20211025_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20211022_15212 (JIT enabled, AOT enabled)
OpenJ9   - 6abb372
OMR      - b898db9
IBM      - 2f2c48b)
JCL - 20210930_01 based on Oracle jdk8u311-b11

[root@junketed1 ~]# podman run -m 4g --rm store/oracle/serverjre:8 java -XshowSettings:vm  -version
VM settings:
    Max. Heap Size (Estimated): 910.50M
    Ergonomics Machine Class: server
    Using VM: Java HotSpot(TM) 64-Bit Server VM

java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
[root@junketed1 ~]# podman run -m 4g --rm openjdk:8-jre java -XshowSettings:vm  -version
VM settings:
    Max. Heap Size (Estimated): 910.50M
    Ergonomics Machine Class: server
    Using VM: OpenJDK 64-Bit Server VM

openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
````

I noticed also some parameter that is still accepted by ibmjava but not by its competitors, but I don't know whether it's related to our issue or not:
````console
[root@dainties1 ~]# podman run -m 4g --rm ibmjava:8-jre java -XshowSettings:vm -XX:MaxRAMPercentage=50 -version
VM settings:
    Max. Heap Size (Estimated): 908.44M
    Ergonomics Machine Class: client
    Using VM: IBM J9 VM

java version "1.8.0_311"
Java(TM) SE Runtime Environment (build 8.0.7.0 - pxa6480sr7-20211025_01(SR7))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20211022_15212 (JIT enabled, AOT enabled)
OpenJ9   - 6abb372
OMR      - b898db9
IBM      - 2f2c48b)
JCL - 20210930_01 based on Oracle jdk8u311-b11

[root@dainties1 ~]# podman run -m 4g --rm openjdk:8-jre java -XshowSettings:vm -XX:MaxRAMPercentage=50 -version
Improperly specified VM option 'MaxRAMPercentage=50'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

[root@dainties1 ~]# podman run -m 4g --rm store/oracle/serverjre:8 java -XshowSettings:vm -XX:MaxRAMPercentage=50 -version
Improperly specified VM option 'MaxRAMPercentage=50'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
````

**Comment by PYLochou** [comment]
Some additional tests on different types of VM;  RHEL 7 runs with cgroup (Podman 1.6.4) and RHEL 8 runs with cgroupv2 (Podman 3.3.1).  I instanciated VMs with 2 and 8 GB but always ran the same command (podman run -m 4g --rm <image> -XshowSettings:vm -version) to emphasize the fact that the IBM Java image does not compute Max Heap Size the same way as Oracle JRE and OpenJRE do:

| | RHEL 7 2GB | RHEL 7 8GB | RHEL 8 2GB | RHEL 8 8GB
| -------- | -------- | -------- | -------- | -------- 
| ibmjava:8-jre | 512.00M | 3.00G | 512.00M | 512.00M
| store/oracle/serverjre:8 | 910.50M | 910.50M | 405.50M | 1.69G
| openjdk:8-jre | 910.50M | 910.50M | 405.50M | 1.69G

The most problematic result is of course Max Heap Size = 512MB in cgroupv2, even in the case of a fat VM :(  OOME are raised fast with our product using IBM Java.

**Comment by zhangs-ibm** [comment]
If this issue connect with: https://github.com/docker/for-mac/issues/6118 ?
The `/sys/fs/cgroup/memory/memory.limit_in_bytes` is missing at the new version of Mac docker container, while eclipse ORM project (which J9 JVM depends on) read this file to know if it's running at the container environment, code ref: https://github.com/eclipse/omr/blob/b5643d019207e22e3a6bcb49d09069200289b639/port/unix/omrsysinfo.c#L5941-L5945

**Comment by zhangs-ibm** [comment]
@lgrateau , Hi Laurent, I found open JDK has the same issue, the test result is not same with yours:
```
docker run -m 4GB --rm openjdk:8-jre java -XshowSettings:vm -version
Unable to find image ‘openjdk:8-jre’ locally
8-jre: Pulling from library/openjdk
0e29546d541c: Pull complete 
9b829c73b52b: Pull complete 
cb5b7ae36172: Pull complete 
99ce012bef04: Pull complete 
22dc2a72d098: Pull complete 
9c69a57e10d9: Pull complete 
Digest: sha256:c0ab1c0631266ef9420a414726a790733a2561efc5f4fa2f9b8186f4d6b00d53
Status: Downloaded newer image for openjdk:8-jre
VM settings:
  Max. Heap Size (Estimated): 665.00M
  Ergonomics Machine Class: server
  Using VM: OpenJDK 64-Bit Server VM
openjdk version “1.8.0_312”
OpenJDK Runtime Environment (build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

**Comment by lgrateau** [comment]
Thanks  for the feeback we will follow the docker issue too.

**Comment by lgrateau** [comment]
seem fixed closing it.
