### ISSUE TITLE
Java 11 - v11.0.16

### ISSUE THREAD

**Issue by bmonteiro** [ibmruntimes/ci.docker#135]
Any plans to release in docker hub the Java11 v11.0.16 ? The ibmjava:11 is using 11.0.11 and the 11.0.16 fixes a lot of CVE's

**Comment by narkedi** [comment]
@bmonteiro We don't have plans to publish Semeru Java11 Certified Edition (which comes with IBM License) at docker hub. Rather you can either use Semeru Runtimes JDK11 Open Edition (which comes with GPL license) from https://hub.docker.com/_/ibm-semeru-runtimes/ which is not a TCK complaint one. 

Incase, you are looking for a TCK complaint JDK you can refer to https://www.ibm.com/support/pages/semeru-runtimes-installation/ on additional details. Thanks !!

**Comment by bmonteiro** [comment]
Thx for the reply

**Comment by narkedi** [comment]
Closing this issue currently, as I hope you have the required information. Do raise a new issue incase of any other queries and apologies for responding late. Thank you !!
