### ISSUE TITLE
Any sh command returned error code 132 on ppc64le/ibmjava:8-sdk image

### ISSUE THREAD

**Issue by caixiangibm** [ibmruntimes/ci.docker#141]
Tried to build on top of ppc64le/ibmjava:8-sdk image, but build always failed as any sh command returned error code 132.
It seems that the problem only occurs on ppc64le, and not for amd64/s390x

https://hub.docker.com/r/ppc64le/ibmjava/tags?page=1&name=8-sdk
digest "sha256:01615017d46542ea6e92555ca3be56564b057faca431997600b223ae1c03680d"

Sample Dockerfile
```
FROM ppc64le/ibmjava:8-sdk
RUN pwd
RUN ls -l
```
But build failed with returned a non-zero code: 132
```
# docker build --no-cache -t mytest:0.1 .
Sending build context to Docker daemon  244.2kB
Step 1/3 : FROM ppc64le/ibmjava:8-sdk
 ---> d41784b5f4e6
Step 2/3 : RUN pwd
 ---> Running in 1168c35df353
The command '/bin/sh -c pwd' returned a non-zero code: 132
```

**Comment by jayasg12** [comment]
Hi @caixiangibm , 
  I tried to create the docker image  with your Dockerfile, which pulled the latest ibmjava:8-sdk from Dockerhub. 
Please find the output below :

docker build --no-cache -t mytest:0.1 .
STEP 1/3: FROM docker.io/library/ibmjava:8-sdk
STEP 2/3: RUN pwd
/
--> 5a4852d3ebe
STEP 3/3: RUN ls -l
total 48
lrwxrwxrwx   1 root   root       7 May 22 14:05 bin -> usr/bin
drwxr-xr-x   2 root   root    4096 Apr 18  2022 boot
drwxr-xr-x   5 root   root     340 Jun  7 03:48 dev
drwxr-xr-x   1 root   root    4096 Jun  2 00:42 etc
drwxr-xr-x   2 root   root    4096 Apr 18  2022 home
lrwxrwxrwx   1 root   root       7 May 22 14:05 lib -> usr/lib
lrwxrwxrwx   1 root   root       9 May 22 14:05 lib64 -> usr/lib64
drwxr-xr-x   2 root   root    4096 May 22 14:05 media
drwxr-xr-x   2 root   root    4096 May 22 14:05 mnt
drwxr-xr-x   1 root   root    4096 Jun  6 22:23 opt
dr-xr-xr-x 459 nobody nogroup    0 Jun  7 03:48 proc
drwx------   1 root   root    4096 Jun  6 22:23 root
drwxr-xr-x   1 root   root    4096 Jun  7 03:48 run
lrwxrwxrwx   1 root   root       8 May 22 14:05 sbin -> usr/sbin
drwxr-xr-x   2 root   root    4096 May 22 14:05 srv
dr-xr-xr-x  12 nobody nogroup    0 May  3 12:00 sys
drwxrwxrwt   1 root   root    4096 Jun  6 22:24 tmp
drwxr-xr-x   1 root   root    4096 May 22 14:05 usr
drwxr-xr-x   1 root   root    4096 Jun  6 22:24 var
COMMIT mytest:0.1
--> ddd8c16cbaf
Successfully tagged localhost/mytest:0.1


root@1d85e2749782:/# java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 8.0.8.5 - pxl6480sr8fp5-20230418_01(SR8 FP5))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux ppc64le-64-Bit Compressed References 20230417_49632 (JIT enabled, AOT enabled)
OpenJ9   - 085a542
OMR      - 9f28c98
IBM      - 68444b7)
JCL - 20230329_01 based on Oracle jdk8u371-b11


If you still see an issue with ppcle , request to check processor on server on which docker is  run 

Ex : cat /proc/cpuinfo
processor	: 0
cpu		: **POWER9** (architected), altivec supported
clock		: 2500.000000MHz
revision	: 2.2 (pvr 004e 0202)


As IBM Java is built on ubuntu 22.04, processor has to be power9 or power10.

**Comment by caixiangibm** [comment]
It's "POWER8" on my side

cat /proc/cpuinfo
processor	: 0
cpu		: POWER8 (architected), altivec supported
clock		: 2893.000000MHz
revision	: 2.0 (pvr 004d 0200)

**Comment by jayasg12** [comment]
Hi @caixiangibm ubuntu22.04 ppcle doesn't support power8. Please run on Power9 servers. Thanks !!

**Comment by jayasg12** [comment]
@caixiangibm can this be closed ?

**Comment by caixiangibm** [comment]
Sure, I will close this.
