### ISSUE TITLE
Issues with ibmjava/8/sdk/alpine/Dockerfile

### ISSUE THREAD

**Issue by mimaison** [ibmruntimes/ci.docker#17]
There are multiple issues with the current Docker file for Alpine:
- The checksum for x86_64 (https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/sdk/alpine/Dockerfile#L45) does not match any checksums listed in the YML file [1]

- The specified Java version 1.8.0_sr5 (https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/sdk/alpine/Dockerfile#L39) does exist in the YML file [1]. So the command that is finding the URL (https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/sdk/alpine/Dockerfile#L71) actually matchs 2 releases:
```
cat index.yml | sed -n '/1.8.0_sr5/{n;p}' | sed -n 's/\s*uri:\s//p' | tr -d '\r'
https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.5.1/linux/x86_64/ibm-java-sdk-8.0-5.1-x86_64-archive.bin
https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/8.0.5.5/linux/x86_64/ibm-java-sdk-8.0-5.5-x86_64-archive.bin
```
This causes wget to download both files and it actually concatenate both of them into a single `/tmp/ibm-java.bin` file !

[1] https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/sdk/linux/x86_64/index.yml

**Comment by dinogun** [comment]
@mimaison Hi, PR #18 should fix the problem, please check if the latest commit resolves it for you. Thanks

**Comment by mimaison** [comment]
Yes it works now ! Thanks
