### ISSUE TITLE
Update Java SDK in docker

### ISSUE THREAD

**Issue by fengxue-IS** [ibmruntimes/ci.docker#27]
The `ibmjava:latest` image is currently using Java8 SR5 FP11.
We should consider updating this

**Comment by dinogun** [comment]
The current target date for the next update is May 11 (Java 8 SR5 FP15 - 8.0.5.15).

**Comment by dinogun** [comment]
New [images](https://hub.docker.com/r/library/ibmjava/tags/) now available for Version Java 8 SR5 FP15 - 8.0.5.15
