### ISSUE TITLE
Produce IBM JRE dockerfile for RHEL

### ISSUE THREAD

**Issue by arthurdm** [ibmruntimes/ci.docker#34]
Hey,

I understand that we cannot publish an IBM JRE image based on RHEL on Docker Hub due to RHEL being proprietary - however, we could provide a Dockerfile that customers use to build their own RHEL image (inside their RHEL-licensed environment).

The WebSphere Liberty GitHub repo started something similar (https://github.com/WASdev/ci.docker/tree/master/ga/developer/rhel), but as you can see the Dockerfile is not as nice as it could be since there's no IBM JRE based on RHEL that we can start `FROM`.  

If I do a PR that adds such Dockerfile, would this GitHub community keep it up to date with JRE releases, etc?

**Comment by arthurdm** [comment]
This is what I had in mind: https://github.com/arthurdm/ci.docker-1/blob/master/ibmjava/8/jre/rhel/Dockerfile

If you guys agree, I can work on putting this into `update.sh` so that we build this Dockerfile automatically.

**Comment by dinogun** [comment]
Seems ok to me since all we are looking for is to maintain the Dockerfile. PR would be welcome !

**Comment by arthurdm** [comment]
Fixed by PR #39
