### ISSUE TITLE
SDK / Alpine

### ISSUE THREAD

**Issue by netflash** [ibmruntimes/ci.docker#4]
https://github.com/ibmruntimes/ci.docker/tree/master/ibmjava/8/sdk
says that there should be an alpine, however it's not true.

I guess README should be consistent with reality. 
Are you going to add it at some point ?

**Comment by dinogun** [comment]
Hi, we had planned to provide Alpine for the JRE and SFJ images only. Thank you for pointing the error in the README. However if you are interested in an Alpine image for the SDK, we can certainly do that. If you dont mind, can you tell me how you plan to use the Alpine SDK image, Thank You

**Comment by dnwe** [comment]
@dinogun we would also be interesting in an SDK image based on alpine if you can provide one.  Currently all of our other Jenkins build slave images are based on alpine, apart from the Java SDK one which is ubuntu.

**Comment by netflash** [comment]
@dinogun same pattern here. Everything is alpine except this one.
We're using SDK image to produce a jar with [gradle](https://gradle.org/)

**Comment by dinogun** [comment]
Thanks for the inputs, I have merged the code for adding SDK alpine images along with support for Alpine 3.6 and glibc 2.25-r0. Will push it to docker tomorrow.

**Comment by dinogun** [comment]
The sdk-alpine image is now available on hub.docker and it is based on Alpine 3.6 (including the sfj-alpine and the jre-alpine ones). @dnwe and @netflash , please let me know if it works for you as 3.6 seems to have some breaking changes (though I dont expect it to break ibmjava as we are still dependent on glibc). Thanks

**Comment by netflash** [comment]
Hm... I don't see any changes neither here [https://hub.docker.com/r/ibmcom/ibmjava/tags/](https://hub.docker.com/r/ibmcom/ibmjava/tags/) nor here [https://hub.docker.com/r/ibmcom/ibmjava/](https://hub.docker.com/r/ibmcom/ibmjava/)

**Comment by dinogun** [comment]
Is there any reason why you are not using the official images ?
https://hub.docker.com/r/library/ibmjava/tags/
I have updated the ibmcom ones now, but please note that we do not update these images as often as the official images (wrt OS fixes)
https://hub.docker.com/r/ibmcom/ibmjava/tags/

**Comment by dinogun** [comment]
Closing as the images are now available.

**Comment by netflash** [comment]
@dinogun actually no reasons, switching to `library/ibmjava` ones.
Thank you!
