### ISSUE TITLE
Busybox, openSSL vulnerabilities

### ISSUE THREAD

**Issue by gdurai78** [ibmruntimes/ci.docker#44]
<img width="1673" alt="screen shot 2018-09-07 at 3 30 42 pm" src="https://user-images.githubusercontent.com/6852560/45242947-a9a93c80-b2b7-11e8-8432-5b3e7e34aaf9.png">

Vulnerability Advisor reported the attached issue with Busybox and openssl. We use the following for our docker containers. Do we have any ETA to address this vulnerabilities?

ibmjava:8-jre-alpine

**Comment by MHBauer** [comment]
I see `BusyBox v1.27.2` and `OpenSSL 1.0.2o  27 Mar 2018` inside the current-ish image, ID:`3a52524d9e1e`.

**Comment by dnwe** [comment]
@gdurai78 make sure you're building your image with `docker build --pull …` so that the base image is refreshed with the latest one published to docker hub on every build

**Comment by gdurai78** [comment]
Sounds good, Thanks
