### ISSUE TITLE
support of UseContainerSupport flag in the s390 architecture

### ISSUE THREAD

**Issue by lgrateau** [ibmruntimes/ci.docker#45]
It's seems the flag -XX:+UseContainerSupport is not taken into account for the s390x/ibmjava architecture.
This leads to OOM exceptions that kill the container. The other architecture amd64 and ppa64le work correctly.
My investigation is that the memory computation inside the jre ibm docker image for S390x is not correct. (Same behavior that we have previously without this flag set in the ibm jre docker 
image).

**Comment by dinogun** [comment]
Hi @lgrateau, thanks for reporting, trying to recreate this, will keep you posted.

**Comment by ashu-mehra** [comment]
@lgrateau I tried using docker image https://hub.docker.com/r/s390x/ibmjava/ but it seems to be honoring the container limit as far as Java heap is concerned.
I started the container with 512MB memory and ran `java -verbose:sizes` to check the default max heap size:
```
# java -verbose:sizes -version
  -Xmx256M          memory maximum
```
If I run with `-XX:-UseContainerSupport` to disable container support, then Xmx gets set to 512M (which is the same if running on host):
```
# java -XX:-UseContainerSupport -verbose:sizes -version
  -Xmx512M        memory maximum
```

Can you please tell more the about the problem you are facing. It will be useful if you can share how you came to the conclusion that the memory computation is not correct? Are there any specific steps to be followed to recreate the issue?

**Comment by dinogun** [comment]
It could also mean that a component other than the heap is causing the OOM (Eg Code cache, native mem etc). Do you have any corefiles that you can share with us. (Probably not if the container is getting killed). You can try turning on verbose:gc

**Comment by ashu-mehra** [comment]
Can you please check the output of `dmesg` which logs some information when container gets killed because of oom-killer and share it here.
You would see something like the output mentioned in this thread https://serverfault.com/questions/788661/how-does-docker-deal-with-oom-killer-and-memory-limits.

**Comment by lgrateau** [comment]
Thanks i will re-test and attach informations.

**Comment by lgrateau** [comment]
We have updated our kubernetes version +docker version 1.10 and 18.0.0.3 and don't encountered any issue. So i think you can close this issue.

**Comment by dinogun** [comment]
Closing per above.
