### ISSUE TITLE
Bump up Alpine to use 3.8

### ISSUE THREAD

**Issue by mastersingh24** [ibmruntimes/ci.docker#51]
Most images are now using Alpine 3.8

**Comment by dinogun** [comment]
The [OpenJ9](https://github.com/AdoptOpenJDK/openjdk-docker/blob/master/8/jdk/alpine/Dockerfile.openj9.releases.full) images are already using it for a while, will update, thanks

**Comment by dnwe** [comment]
@dinogun is it worth jumping straight to 3.9 now that has been released and has migrated back to OpenSSL rather than LibreSSL?

**Comment by dinogun** [comment]
Was planning on updating the OpenJ9 images to 3.9 first.

**Comment by dinogun** [comment]
We now have alpine:3.10 as the base.
