### ISSUE TITLE
Broken links to ibmjava 8 dockerfiles

### ISSUE THREAD

**Issue by ajlohr** [ibmruntimes/ci.docker#57]
All the links in the README at https://github.com/ibmruntimes/ci.docker/tree/master/ibmjava/8/jre lead to 404

For example, https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/jre/x86_64/ubuntu

Also all the links to dockerfiles on Docker Hub too https://hub.docker.com/r/ibmcom/ibmjava/

**Comment by dinogun** [comment]
Should be fixed now. Thanks
