### ISSUE TITLE
Q: setting SSL?

### ISSUE THREAD

**Issue by composer22** [ibmruntimes/ci.docker#63]
Trying to use: ibmjava:8-jre-alpine along with spring boot.

We've been using this image for over a year, including latest, and we are now getting exceptions around TLS 1.2.  Such as this example
```
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://FOO": Connection reset; nested exception is java.net.SocketException: Connection reset
```

or
```
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at com.ibm.jsse2.at.a(at.java:145) ~[na:8.0 
```
Works fine in openjdk and using cURL

Q: are there any special settings we need to include in this image to configure?  Tried 

- Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2 
- Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

to no affect

as recommended:

https://www-01.ibm.com/support/docview.wss?uid=nas8N1022279

Any ideas appreciated.

**Comment by amnpandey** [comment]
Please add "-Dcom.ibm.jsse2.overrideDefaultTLS = true" and check if it works

We need to add all the below 3 for TLSv1.2:
-Dcom.ibm.jsse2.overrideDefaultTLS = true
-Djdk.tls.client.protocols = TLSv1.2
-Dhttps.protocols = TLSv1.2

**Comment by dinogun** [comment]
@composer22 Did the above help ? Were you able to fix your issue ?

**Comment by dinogun** [comment]
closing as fixed.
