### ISSUE TITLE
ibmjava 8 jre image giving "IllegalAccessError" on server startup

### ISSUE THREAD

**Issue by vermavikrant** [ibmruntimes/ci.docker#65]
Once every few weeks my team does a rebuild of our base image. 
Recently after pulling latest ibmjava 8 jre image, our server is throwing exception at startup (error copied below)

Our codebase is in scala.
War file packaged by sbt
Server is jetty runner (latest).

Exception from logs:
```
2019-04-18 13:31:36.173:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@432bd1c0{/,file:///tmp/jetty-0.0.0.0-8080-project-name_2.12-0.1.0.war-_-any-6799891172187585100.dir/webapp/,UNAVAILABLE}{file:///usr/local/share/jetty/project-name_2.12-0.1.0.war}
java.lang.IllegalAccessError: Receiver class java/lang/Class must be the current class or a subtype of interface scala/collection/MapLike
    at scala.collection.MapLike.newBuilder$(MapLike.scala:74)
    at scala.collection.AbstractMap.newBuilder(Map.scala:59)
    at akka.actor.setup.ActorSystemSetup.get(ActorSystemSetup.scala:65)
```

On trying to start server locally and pointing to latest ibm jre 8, we are seeing same issues.
Whatever the previous version of ibm jre 8 was, it was working well locally as well by ibmjava 8 jre docker image.

**Comment by DanHeidinga** [comment]
This looks a lot like APAR IJ15455: https://www-01.ibm.com/support/docview.wss?uid=swg1IJ15455

The APAR mentions a GPF but we've also seen it manifest as an IllegalAccessError.  Updates to the APAR are in progess

**Comment by pshipton** [comment]
i.e. the fix should be in the next IBM release, FP35, due out at the end of April.

**Comment by dinogun** [comment]
Thanks @DanHeidinga @pshipton. Will keep this open till we can confirm with FP35.

**Comment by dinogun** [comment]
@vermavikrant Now that FP35 is out, can you please confirm if this fixes your issue.

**Comment by dinogun** [comment]
Closing as fixed. Please re-open if needed.
