### ISSUE TITLE
Docker image uses old version of Ubuntu LTS

### ISSUE THREAD

**Issue by msmigiel** [ibmruntimes/ci.docker#67]
I've noticed that the Docker image for ibmjava uses Ubuntu 16.04 LTS as its starting point. Are there any plans to upgrade to the latest LTS release, 18.04? I'm working with `buildah` and logged an issue with that team and in our investigation, it's possible that this old version of Ubuntu is part of our problem.

https://github.com/containers/buildah/issues/1546

**Comment by dinogun** [comment]
Closing as the latest images are 18.04
