### ISSUE TITLE
Please tag the image `ibmjava:8-sfj-alpine` with alpine 3.7

### ISSUE THREAD

**Issue by abhishek-mane** [ibmruntimes/ci.docker#79]
Recently as part of this PR => https://github.com/ibmruntimes/ci.docker/pull/78/files, the base OS has been changed from **alpine3.7** to **alpine3.10**. The tag was suppose to be created before overwriting the new change. Because of this change our Dockerbuilds are failing at the point where its dependent on alpine3.7.

**Comment by abhishek-mane** [comment]
@jayasg12

**Comment by jayasg12** [comment]
Hi @abhishek-mane I believe this issue is resolved. Closing this issue. Please feel free to re-open an issue if any concern
