### ISSUE TITLE
JRE docker images do not build with latest 1.8.0_sr6fp6 change (while SDK ones do)

### ISSUE THREAD

**Issue by fred06fr** [ibmruntimes/ci.docker#87]
Trying to build the docker https://github.com/ibmruntimes/ci.docker/blob/master/ibmjava/8/jre/ubi-min/Dockerfile for example fails, because it does not find 1.8.0_sr6fp6 in https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/jre/linux/x86_64/index.yml
Apparently the fixpack exists in SDKs (https://public.dhe.ibm.com/ibmdl/export/pub/systems/cloud/runtimes/java/meta/sdk/linux/x86_64/index.yml) but not in JREs.
So the SDK images build, but not the JRE ones. 
Same for all base images, this is not limited to ubi-min.

**Comment by dinogun** [comment]
@fred06fr We have had to pull back 1.8.0_sr6fp6 as it was broken. Will be reverting to the sr6fp5, should happen tomorrow.

**Comment by dinogun** [comment]
Reverted to sr6fp5 and the images are now available.
